version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Changing the desired count on tasks
      - aws ecs update-service --cluster devkit-api --service devkit-service --desired-count 0
      - echo Changing the desired count on aoutscaling group
      - aws autoscaling update-auto-scaling-group --auto-scaling-group-name EC2ContainerService-devkit-api-EcsInstanceAsg-134070FPMLR8P --desired-capacity 0 --min-size 0 --max-size 4
  post_build:
    commands:
      - echo 'Finished'

